"""ReviewTrigger — background review and PatternMiner scheduling.

Extracted from TerraAgent._maybe_review().

Determines whether to trigger a background review based on:
    - Iteration count (≥ 5)
    - User intervention (user messages during task)
    - ask_user calls (agent was stuck)
    - Loop detection (screen loops)
"""

from __future__ import annotations

import logging
from dataclasses import asdict
from typing import Any

from config.settings import config

logger = logging.getLogger(__name__)


def _run_auto_remediate(game: str) -> None:
    """Check learning metrics and take automatic corrective action.

    Runs in a background daemon thread.  Each rule has a threshold and a
    minimum sample size to avoid over-reacting to noise.
    """
    try:
        from src.agent.learning_metrics import compute_metrics
        metrics = compute_metrics(game=game, window_days=7)
    except Exception as e:
        from src.utils.errors import safe_log
        safe_log(logger, "warning", f"Auto-remediate metrics compute failed: {e}")
        return

    task_count = metrics.get("task_count", 0)
    if task_count < 5:
        return  # Not enough data for reliable decisions

    # ── Rule 1: Help/harm ratio dangerously low → aggressive cleanup ──
    help_harm = metrics.get("help_harm_ratio", 1.0)
    if help_harm < 0.5:
        logger.warning(
            "Auto-remediate: help/harm ratio %.2f < 0.5 — running aggressive stale cleanup",
            help_harm,
        )
        try:
            from src.tools.remember import cleanup_stale_memories
            n = cleanup_stale_memories(game, stale_days=5, low_help_harm_ratio=0.4)
            logger.info("Auto-remediate: cleaned %d stale memories (aggressive mode)", n)
        except Exception as e:
            from src.utils.errors import safe_log
            safe_log(logger, "warning", f"Auto-remediate cleanup failed: {e}")

    # ── Rule 2: Fast-chain success rate collapsing → mark skills stale ──
    # Guard: disabled by default — auto-stale marking feeds the broken
    # skill_refiner pipeline and produces garbage v2 variants.
    if config.agent.enable_skill_refinement:
        fc_rate = metrics.get("fast_chain_success_rate", 1.0)
        fc_usage = metrics.get("fast_chain_usage_rate", 0.0)
        if fc_rate < 0.3 and fc_usage > 0.05:
            logger.warning(
                "Auto-remediate: fast_chain success rate %.2f < 0.3 — marking skills",
                fc_rate,
            )
            try:
                import time as _time
                from src.memory.skill_db import skill_db
                # Skip skills created/updated within the last hour — they
                # may have been freshly generated by background review and
                # their coordinates are still valid.  Sort oldest first
                # so skills with the most drift get marked first.
                _skip_newer_than = _time.time() - 3600
                rows = skill_db.conn.execute(
                    """SELECT name FROM skills_data
                       WHERE verified = 1 AND file_mtime < ?
                       ORDER BY file_mtime ASC
                       LIMIT 5""",
                    (_skip_newer_than,),
                ).fetchall()
                from src.tools.skill_refiner import mark_skill_potentially_stale
                for r in rows:
                    mark_skill_potentially_stale(r["name"], game, reason="auto_remediate_low_fc_rate")
                    logger.info("Auto-remediate: marked skill '%s' as potentially stale", r["name"])
            except Exception as e:
                from src.utils.errors import safe_log
                safe_log(logger, "warning", f"Auto-remediate skill marking failed: {e}")

    # ── Rule 3: First-try rate extremely low → diagnostic memory ──
    first_try = metrics.get("first_try_rate", 1.0)
    if first_try < 0.15 and task_count >= 10:
        logger.warning(
            "Auto-remediate: first_try rate %.2f < 0.15 — writing diagnostic memory",
            first_try,
        )
        try:
            from src.tools.remember import _index_memory
            import time as _time
            name = f"diag{int(_time.time() * 1_000_000)}"
            body = (
                f"【自动诊断 — {game}】近7天 {task_count} 个任务中，首次成功率仅 "
                f"{round(first_try * 100)}%。成功率 {round(metrics.get('success_rate', 0) * 100)}%，"
                f"平均 {metrics.get('avg_iterations', 0)} 轮/任务，"
                f"用户干预频率 {round(metrics.get('ask_user_frequency', 0) * 100)}%。\n"
                f"建议：检查是否有全局性问题（ADB连接、OCR识别率、模拟器性能）。"
            )
            _index_memory(name, game, "pattern_miner, 诊断, 永久", body,
                         source="pattern_miner")
            logger.info("Auto-remediate: diagnostic memory written for game=%s", game)
        except Exception as e:
            from src.utils.errors import safe_log
            safe_log(logger, "warning", f"Auto-remediate diagnostic failed: {e}")


def _run_miner_and_cleanup(game: str) -> None:
    """Run PatternMiner, stale memory cleanup, and observation cleanup together.

    Called via daemon thread from ReviewTrigger.maybe_trigger().  All three
    use the same scheduling interval; running them together avoids multiple
    scheduling points.
    """
    try:
        from src.intelligence.pattern_miner import run_pattern_miner_if_due
        saved = run_pattern_miner_if_due(game)
        if saved:
            logger.info("PatternMiner: saved %d findings for game=%s", saved, game)
        from src.tools.remember import cleanup_stale_memories
        n_stale = cleanup_stale_memories(game)
        if n_stale:
            logger.info("Stale memory cleanup: removed %d memories for game=%s",
                       n_stale, game)
        # ── Log table cleanup ──
        try:
            from src.memory.memory_db import memory_db
            n_logs = memory_db.cleanup_old_logs(keep_days=30)
            if n_logs:
                logger.info("Log cleanup: removed %d old rows (game=%s)", n_logs, game)
        except Exception:
            pass
        # ── FTS5 rebuild (deferred) ──
        try:
            from src.memory.memory_db import memory_db
            memory_db.rebuild_fts_if_dirty()
        except Exception:
            pass
        # ── Observation data retention cleanup ──
        try:
            from src.agent.observation_store import cleanup_old_sessions
            obs_result = cleanup_old_sessions(game, keep_days=30, dry_run=False)
            if obs_result["deleted"] > 0:
                logger.info(
                    "Observation cleanup: removed %d old sessions (~%s MB freed), "
                    "%d sessions kept",
                    obs_result["deleted"], obs_result["freed_mb"], obs_result["kept"],
                )
        except Exception:
            pass  # Non-critical — observation cleanup failure shouldn't block
    except Exception as e:
        from src.utils.errors import safe_log
        safe_log(logger, "warning", f"PatternMiner + cleanup failed: {e}")


class ReviewTrigger:
    """Backend review orchestrator — condition check + spawn + PatternMiner."""

    def __init__(self, memory_db: Any, config: Any) -> None:
        self._memory_db = memory_db
        self._config = config

    def maybe_trigger(
        self,
        state: Any,          # AgentState
        loop_guard: Any,     # LoopGuard
        review_msgs: list[dict[str, Any]] | None = None,
        matching_skills: list[dict[str, Any]] | None = None,
        task_description: str = "",
    ) -> None:
        """Conditionally trigger background review + periodic PatternMiner.

        Called after each task completes.  Decides whether a review is
        warranted and spawns background extraction if so.
        """
        has_user_intervention = state._user_msg_count > 0
        has_ask_user = state._ask_user_count > 0
        has_loops = loop_guard.loop_detection_count > 0
        enough_iters = state.iteration_count >= 5

        if not (enough_iters or has_user_intervention or has_ask_user or has_loops):
            return

        msgs = review_msgs or state.conversation_history
        if not msgs:
            return

        from src.agent.background_review import spawn_background_review

        matched_names = [
            s["name"] for s in (matching_skills or [])
            if s.get("name")
        ] if matching_skills else None

        spawn_background_review(
            msgs,
            state.game,
            task_description=task_description or state.task_description,
            screen_w=state.screen_w,
            screen_h=state.screen_h,
            failure_signals=[asdict(s) for s in state.failure_signals],
            matched_skill_names=matched_names,
            iterations=state.iteration_count,
            ask_user_count=state._ask_user_count,
            user_msg_count=state._user_msg_count,
        )

        # ── Periodic PatternMiner + stale cleanup ──
        # Uses increment_pattern_miner_counter / run_pattern_miner_if_due from
        # pattern_miner.py (single shared counter key, not duplicated across modules).
        try:
            from src.intelligence.pattern_miner import (
                increment_pattern_miner_counter,
                run_pattern_miner_if_due,
            )
            increment_pattern_miner_counter(state.game)
            import threading
            t = threading.Thread(
                target=_run_miner_and_cleanup,
                args=(state.game,),
                daemon=True,
            )
            t.start()
        except Exception:
            from src.utils.errors import safe_log
            safe_log(logger, "warning", "PatternMiner skipped")

        # ── Auto-remediation based on learning metrics ──
        # Runs in background; checks recent metrics and takes corrective action
        # when indicators degrade beyond thresholds.
        try:
            t2 = threading.Thread(
                target=_run_auto_remediate,
                args=(state.game,),
                daemon=True,
            )
            t2.start()
        except Exception:
            from src.utils.errors import safe_log
            safe_log(logger, "warning", "Auto-remediation skipped")
