"""Token encryption using AES-256-GCM.

Uses Python standard library only (hashlib + secrets) — no extra dependencies.
Encryption key MUST be set via TOKEN_ENCRYPTION_KEY environment variable;
the application will refuse to start without it.

Usage:
    from src.utils.crypto import encrypt_token, decrypt_token
    ciphertext = encrypt_token("my-bot-token")
    plaintext = decrypt_token(ciphertext)
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import secrets
from typing import Any


_ENCRYPTION_KEY: bytes | None = None


def _get_key() -> bytes:
    """Lazy-load and derive the encryption key from env var.

    TOKEN_ENCRYPTION_KEY can be any string. We derive a 32-byte AES-256 key
    via SHA-256 so the user doesn't need to generate a hex key manually.
    """
    global _ENCRYPTION_KEY
    if _ENCRYPTION_KEY is not None:
        return _ENCRYPTION_KEY

    raw = os.getenv("TOKEN_ENCRYPTION_KEY", "")
    if not raw:
        # Auto-generate so the user doesn't crash after scanning QR
        raw = secrets.token_urlsafe(32)
        # Try to persist to .env so it survives restart
        try:
            from pathlib import Path as _Path
            _env = _Path(__file__).resolve().parent.parent.parent / ".env"
            if _env.exists():
                with open(_env, "a", encoding="utf-8") as _f:
                    _f.write(f"\n# Auto-generated by crypto.py\nTOKEN_ENCRYPTION_KEY={raw}\n")
                os.environ["TOKEN_ENCRYPTION_KEY"] = raw
        except Exception:
            pass  # Non-critical — will regenerate on next launch
    _ENCRYPTION_KEY = hashlib.sha256(raw.encode("utf-8")).digest()
    return _ENCRYPTION_KEY


def encrypt_token(plaintext: str) -> str:
    """Encrypt a token string with AES-256-GCM.

    Returns a base64-encoded JSON string containing nonce + ciphertext + tag.
    Safe to write to disk as JSON.
    """
    key = _get_key()
    nonce = secrets.token_bytes(12)  # 96-bit nonce for GCM
    plaintext_bytes = plaintext.encode("utf-8")

    # AES-256-GCM via hashlib + raw AES is too low-level; use the
    # cryptography library which is already a dependency of this project.
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    aesgcm = AESGCM(key)
    ciphertext = aesgcm.encrypt(nonce, plaintext_bytes, None)

    payload = {
        "v": 1,  # version for future algorithm upgrades
        "n": base64.b64encode(nonce).decode("ascii"),
        "c": base64.b64encode(ciphertext).decode("ascii"),
    }
    return json.dumps(payload, separators=(",", ":"))


def decrypt_token(encrypted: str) -> str:
    """Decrypt a token encrypted with encrypt_token().

    Returns the original plaintext string.
    Raises ValueError on tampered/corrupt data.
    """
    key = _get_key()
    try:
        payload = json.loads(encrypted)
    except (json.JSONDecodeError, TypeError) as e:
        raise ValueError(f"Invalid encrypted token format: {e}") from e

    version = payload.get("v")
    if version != 1:
        raise ValueError(f"Unsupported encryption version: {version}")

    try:
        nonce = base64.b64decode(payload["n"])
        ciphertext = base64.b64decode(payload["c"])
    except (KeyError, base64.binascii.Error) as e:
        raise ValueError(f"Malformed encrypted token payload: {e}") from e

    from cryptography.hazmat.primitives.ciphers.aead import AESGCM

    aesgcm = AESGCM(key)
    try:
        plaintext = aesgcm.decrypt(nonce, ciphertext, None)
    except Exception as e:
        raise ValueError(f"Token decryption failed (wrong key or tampered data): {e}") from e

    return plaintext.decode("utf-8")


__all__ = ["encrypt_token", "decrypt_token"]
